enum PostType { text, image, video, product, review, update, photos }

class PostModel {
  final String id;
  final String authorName;
  final String authorAvatar;
  final String authorColor;
  final String time;
  final String text;
  final PostType type;
  final String? tag;
  final String? imageEmoji;
  final String? imageBg;
  final bool isSponsored;
  final bool isVerified;
  final int likes;
  final int comments;
  final int shares;
  final bool isLiked;
  final List<String> imageUrls;
  final String authorId;
  final String authorImage;
  final bool authorIsFactory;
  final String authorFactoryId;
  final bool isAutogenerated;
  final String sourceEntity;
  final Map<String, dynamic>? metadata;

  const PostModel({
    required this.id,
    required this.authorName,
    required this.authorAvatar,
    required this.authorColor,
    required this.time,
    required this.text,
    this.type = PostType.text,
    this.tag,
    this.imageEmoji,
    this.imageBg,
    this.isSponsored = false,
    this.isVerified = false,
    this.likes = 0,
    this.comments = 0,
    this.shares = 0,
    this.isLiked = false,
    this.imageUrls = const [],
    this.authorId = '',
    this.authorImage = '',
    this.authorIsFactory = false,
    this.authorFactoryId = '',
    this.isAutogenerated = false,
    this.sourceEntity = '',
    this.metadata,
  });

  PostModel copyWith({bool? isLiked, int? likes}) {
    return PostModel(
      id: id,
      authorName: authorName,
      authorAvatar: authorAvatar,
      authorColor: authorColor,
      time: time,
      text: text,
      type: type,
      tag: tag,
      imageEmoji: imageEmoji,
      imageBg: imageBg,
      isSponsored: isSponsored,
      isVerified: isVerified,
      likes: likes ?? this.likes,
      comments: comments,
      shares: shares,
      isLiked: isLiked ?? this.isLiked,
      imageUrls: imageUrls,
      authorId: authorId,
      authorImage: authorImage,
      authorIsFactory: authorIsFactory,
      authorFactoryId: authorFactoryId,
      isAutogenerated: isAutogenerated,
      sourceEntity: sourceEntity,
      metadata: metadata,
    );
  }
}
