import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:share_plus/share_plus.dart';
import '../data/app_data.dart';
import '../models/post_model.dart';
import '../screens/auth/login_modal.dart';
import '../services/api_client.dart';
import '../services/auth_service.dart';
import '../services/l10n.dart';
import '../theme/app_theme.dart';
import 'common_widgets.dart';
import 'shell_widgets.dart';
import 'timeline_meta.dart';
import '../screens/opportunities/opportunities_screen.dart' show tri;

/// Timeline post, styled like the website's `Post` component (white card, autogenerated
/// activity posts rendered as a coloured title bar plus label/value rows — never raw IDs).
class PostCard extends StatefulWidget {
  final PostModel post;
  final VoidCallback? onTap;

  const PostCard({super.key, required this.post, this.onTap});

  @override
  State<PostCard> createState() => _PostCardState();
}

class _PostCardState extends State<PostCard> {
  late bool _liked;
  late int _likes;
  bool _showComments = false;
  final _commentCtrl = TextEditingController();
  final List<Map<String, String>> _comments = [];
  bool _loadingComments = false;
  bool _commentsLoaded = false;
  int _serverExtraComments = 0;

  @override
  void initState() {
    super.initState();
    _liked = widget.post.isLiked;
    _likes = widget.post.likes;
  }

  @override
  void dispose() {
    _commentCtrl.dispose();
    super.dispose();
  }

  bool _requireLogin() {
    if (AuthService.i.isLoggedIn) return true;
    showAppToast(context, t('post.login_required', 'سجّل الدخول أولاً'));
    LoginModal.show(context);
    return false;
  }

  Future<void> _toggleLike() async {
    if (!_requireLogin()) return;
    final prevLiked = _liked, prevLikes = _likes;
    setState(() {
      _liked = !_liked;
      _likes += _liked ? 1 : -1;
    });
    try {
      final res = await ApiClient.i.post('/posts/${widget.post.id}/likes');
      final data = res['data'];
      if (mounted && data is Map) {
        setState(() {
          _liked = data['liked'] == true;
          _likes = (data['likes_count'] as num?)?.toInt() ?? _likes;
        });
      }
    } on ApiException catch (e) {
      if (!mounted) return;
      setState(() {
        _liked = prevLiked;
        _likes = prevLikes;
      });
      showAppToast(context, '⚠️ ${e.message}');
    }
  }

  Future<void> _toggleComments() async {
    setState(() => _showComments = !_showComments);
    if (!_showComments || _commentsLoaded) return;
    setState(() => _loadingComments = true);
    try {
      final res = await ApiClient.i.get('/posts/${widget.post.id}/comments', query: {'per_page': 50});
      final loaded = ApiClient.list(res['data']).map((c) {
        final u = c['user'] is Map ? Map<String, dynamic>.from(c['user'] as Map) : <String, dynamic>{};
        return {'name': (u['name'] as String?) ?? t('post.default_user', 'مستخدم'), 'text': AppData.tr(c, 'content')};
      }).toList();
      if (mounted) {
        setState(() {
          _comments
            ..clear()
            ..addAll(loaded);
          _commentsLoaded = true;
        });
      }
    } on ApiException catch (e) {
      if (mounted) showAppToast(context, '⚠️ ${e.message}');
    } finally {
      if (mounted) setState(() => _loadingComments = false);
    }
  }

  Future<void> _addComment() async {
    final txt = _commentCtrl.text.trim();
    if (txt.isEmpty || !_requireLogin()) return;
    try {
      await ApiClient.i.post('/posts/${widget.post.id}/comments', body: {'content_${L10n.i.lang}': txt});
      if (!mounted) return;
      setState(() {
        _comments.add({'name': AuthService.i.name.isEmpty ? t('post.default_user', 'مستخدم') : AuthService.i.name, 'text': txt});
        _commentCtrl.clear();
        _serverExtraComments++;
      });
    } on ApiException catch (e) {
      if (mounted) showAppToast(context, '⚠️ ${e.message}');
    }
  }

  void _openFactory() {
    final id = widget.post.metadata?['item_id'];
    if (id != null) context.push('/factory/$id');
  }

  // ───────────────────────── body ─────────────────────────

  Widget _postImage(String url) => CachedNetworkImage(
        imageUrl: url,
        fit: BoxFit.cover,
        placeholder: (_, __) => Container(color: const Color(0xFFEEEEEE)),
        errorWidget: (_, __, ___) => Container(color: const Color(0xFFEEEEEE), child: const Icon(Icons.broken_image_outlined, color: AppColors.muted)),
      );

  Widget _images(List<String> urls) {
    if (urls.isEmpty) return const SizedBox.shrink();
    return Padding(
      padding: const EdgeInsets.only(top: 10),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(8),
        child: SizedBox(
          width: double.infinity,
          height: 220,
          child: urls.length == 1
              ? _postImage(urls.first)
              : ListView.separated(
                  scrollDirection: Axis.horizontal,
                  itemCount: urls.length,
                  separatorBuilder: (_, __) => const SizedBox(width: 3),
                  itemBuilder: (_, i) => SizedBox(width: 260, child: _postImage(urls[i])),
                ),
        ),
      ),
    );
  }

  /// Coloured title bar (`#FDF4E0` / `#7A5600`) used by activity posts.
  Widget _titleBar(String title, {VoidCallback? onTap}) => GestureDetector(
        onTap: onTap,
        child: Container(
          width: double.infinity,
          padding: const EdgeInsets.all(12),
          margin: const EdgeInsets.only(bottom: 12),
          decoration: BoxDecoration(color: const Color(0xFFFDF4E0), borderRadius: BorderRadius.circular(6)),
          child: Row(
            children: [
              const Icon(Icons.edit_outlined, size: 16, color: Color(0xFF7A5600)),
              const SizedBox(width: 8),
              Expanded(child: Text(title, style: GoogleFonts.tajawal(fontSize: 13, fontWeight: FontWeight.w700, color: const Color(0xFF7A5600), height: 1.5))),
            ],
          ),
        ),
      );

  Widget _row(MetaRow r) {
    final long = r.value.length > 15 || r.key.contains('address') || RegExp('activit', caseSensitive: false).hasMatch('${r.key} ${r.label}');
    final values = formatValue(r.value, r.key, r.label);
    final ltr = isLtrValue(r.value, r.key, r.label);
    final pill = Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
      decoration: BoxDecoration(color: const Color(0xFFE6F4EA), borderRadius: BorderRadius.circular(6)),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        mainAxisSize: MainAxisSize.min,
        children: [
          for (final v in values)
            Directionality(
              textDirection: (L10n.i.isRtl && !ltr) ? TextDirection.rtl : TextDirection.ltr,
              child: Text(v, style: GoogleFonts.tajawal(fontSize: 13, fontWeight: FontWeight.w700, color: const Color(0xFF1B5E20), height: 1.5)),
            ),
        ],
      ),
    );
    final label = Text(r.label, style: GoogleFonts.tajawal(fontSize: 13, fontWeight: FontWeight.w500, color: const Color(0xFF333333)));
    return Container(
      width: double.infinity,
      margin: const EdgeInsets.only(bottom: 10),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(6), border: Border.all(color: const Color(0xFFE2E8F0))),
      child: long
          ? Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [label, const SizedBox(height: 8), pill])
          : Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.center, children: [label, Flexible(child: pill)]),
    );
  }

  bool _isLogoRow(MetaRow r) => RegExp(r'logo|الشعار|شعار|logosu', caseSensitive: false).hasMatch('${r.key} ${r.label}');

  /// "Factory logo <name>" — replaces the raw "logo file: <stored file name>" row; the name opens the factory.
  Widget _logoCaption(String name, String? factoryId) {
    final link = GoogleFonts.tajawal(fontSize: 14, fontWeight: FontWeight.w800, color: AppColors.gold, decoration: TextDecoration.underline, decorationColor: AppColors.gold);
    return Container(
      width: double.infinity,
      margin: const EdgeInsets.only(bottom: 10),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(6), border: Border.all(color: const Color(0xFFE2E8F0))),
      child: Wrap(crossAxisAlignment: WrapCrossAlignment.center, spacing: 6, children: [
        Text(tri('شعار مصنع', 'Fabrika logosu', 'Factory logo'), style: GoogleFonts.tajawal(fontSize: 13, fontWeight: FontWeight.w500, color: const Color(0xFF333333))),
        GestureDetector(
          onTap: factoryId == null || factoryId.isEmpty ? null : () => context.push('/factory/$factoryId'),
          child: Text(name, style: factoryId == null || factoryId.isEmpty ? link.copyWith(decoration: TextDecoration.none, color: AppColors.text) : link),
        ),
      ]),
    );
  }

  Widget _autoBody(PostModel p) {
    final content = p.text;
    final allRows = visibleRows(p.metadata, content);
    final hasLogo = allRows.any(_isLogoRow);
    final rows = allRows.where((r) => !_isLogoRow(r)).toList();
    final itemId = '${p.metadata?['item_id'] ?? ''}';
    final factoryId = p.authorFactoryId.isNotEmpty ? p.authorFactoryId : (itemId == 'null' ? '' : itemId);
    final factoryName = cleanName(p.authorName).isNotEmpty ? cleanName(p.authorName) : extractName(contentLead(content));
    final fallback = rows.isEmpty ? contentDetailBody(content) : '';
    final title = activityHeader(contentLead(content));
    final metaImage = [p.metadata?['image_url'], p.metadata?['image_path'], p.metadata?['image']]
        .whereType<String>()
        .firstWhere((u) => u.startsWith('http'), orElse: () => '');
    final images = [...p.imageUrls, if (metaImage.isNotEmpty && !p.imageUrls.contains(metaImage)) metaImage];
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 12),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          _titleBar(title.isNotEmpty ? title : t('post.contact_updated', 'تحديث بيانات الاتصال'), onTap: _openFactory),
          for (final r in rows) _row(r),
          if (hasLogo && factoryName.isNotEmpty) _logoCaption(factoryName, factoryId),
          if (fallback.isNotEmpty)
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(6), border: Border.all(color: const Color(0xFFE2E8F0))),
              child: Text(fallback, style: GoogleFonts.tajawal(fontSize: 13, color: const Color(0xFF333333), height: 1.7)),
            ),
          _images(images),
        ],
      ),
    );
  }

  Widget _plainBody(PostModel p) => Padding(
        padding: const EdgeInsets.only(top: 12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            if (p.text.trim().isNotEmpty) Text(p.text, style: GoogleFonts.tajawal(fontSize: 14, color: AppColors.text, height: 1.7)),
            _images(p.imageUrls),
          ],
        ),
      );

  Widget _action(IconData icon, String label, Color color, VoidCallback onTap) => Expanded(
        child: InkWell(
          onTap: onTap,
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 10),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(icon, size: 18, color: color),
                const SizedBox(width: 5),
                Text(label, style: GoogleFonts.tajawal(fontSize: 12, color: color)),
              ],
            ),
          ),
        ),
      );

  @override
  Widget build(BuildContext context) {
    final p = widget.post;
    final name = cleanName(p.authorName).isEmpty ? t('post.default_user', 'مستخدم') : cleanName(p.authorName);
    const gray = Color(0xFF667085);
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFE5E7EB)),
        boxShadow: [BoxShadow(color: const Color(0xFF101828).withAlpha(10), blurRadius: 2, offset: const Offset(0, 1))],
      ),
      clipBehavior: Clip.antiAlias,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(12, 12, 12, 0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                GestureDetector(
                  behavior: HitTestBehavior.opaque,
                  onTap: () {
                    if (p.authorFactoryId.isNotEmpty) {
                      context.push('/factory/${p.authorFactoryId}');
                    } else if (p.authorId.isNotEmpty && p.authorId != '0') {
                      context.push('/profile/${p.authorId}');
                    }
                  },
                  child: Row(
                  children: [
                    const SizedBox(width: 10),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(name, style: GoogleFonts.tajawal(fontSize: 14.5, fontWeight: FontWeight.w700, color: AppColors.text, height: 1.4)),
                          Text(p.time, style: GoogleFonts.tajawal(fontSize: 11.5, color: gray)),
                        ],
                      ),
                    ),
                  ],
                  ),
                ),
                p.isAutogenerated ? _autoBody(p) : _plainBody(p),
              ],
            ),
          ),
          Container(
            decoration: const BoxDecoration(border: Border(top: BorderSide(color: Color(0xFFF2F4F7)))),
            child: Row(
              children: [
                _action(_liked ? Icons.favorite : Icons.favorite_border, '${t('post.like', 'إعجاب')}${_likes > 0 ? ' ($_likes)' : ''}', _liked ? AppColors.red : const Color(0xFF6B6B6B), _toggleLike),
                _action(Icons.chat_bubble_outline, '${t('post.comment', 'تعليق')}${(p.comments + _serverExtraComments) > 0 ? ' (${p.comments + _serverExtraComments})' : ''}', const Color(0xFF6B6B6B), _toggleComments),
                _action(Icons.share_outlined, t('post.share', 'مشاركة'), const Color(0xFF6B6B6B), () => Share.share('${p.authorName}\n\nhttps://factorya.net')),
              ],
            ),
          ),
          if (_showComments)
            Padding(
              padding: const EdgeInsets.fromLTRB(12, 0, 12, 12),
              child: Column(
                children: [
                  if (_loadingComments) const Padding(padding: EdgeInsets.all(8), child: SizedBox(width: 18, height: 18, child: CircularProgressIndicator(strokeWidth: 2, color: AppColors.gold))),
                  if (!_loadingComments && _comments.isEmpty)
                    Padding(padding: const EdgeInsets.all(8), child: Text(t('post.no_comments', 'لا توجد تعليقات بعد'), style: GoogleFonts.tajawal(fontSize: 12, color: gray))),
                  ..._comments.map((c) => Padding(
                        padding: const EdgeInsets.only(bottom: 7),
                        child: Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            netAvatar(null, c['name']!, size: 28),
                            const SizedBox(width: 7),
                            Expanded(
                              child: Container(
                                padding: const EdgeInsets.all(8),
                                decoration: BoxDecoration(color: AppColors.bg, borderRadius: BorderRadius.circular(10)),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(c['name']!, style: GoogleFonts.tajawal(fontSize: 11.5, fontWeight: FontWeight.w700)),
                                    Text(c['text']!, style: GoogleFonts.tajawal(fontSize: 12, color: const Color(0xFF444444))),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      )),
                  Row(
                    children: [
                      Expanded(
                        child: TextField(
                          controller: _commentCtrl,
                          onSubmitted: (_) => _addComment(),
                          style: GoogleFonts.tajawal(fontSize: 13),
                          decoration: InputDecoration(
                            hintText: t('post.comment_placeholder', 'اكتب تعليقك هنا...'),
                            hintStyle: GoogleFonts.tajawal(fontSize: 12),
                            contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                            border: OutlineInputBorder(borderRadius: BorderRadius.circular(20), borderSide: const BorderSide(color: AppColors.border)),
                            enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(20), borderSide: const BorderSide(color: AppColors.border)),
                            focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(20), borderSide: const BorderSide(color: AppColors.gold)),
                          ),
                        ),
                      ),
                      const SizedBox(width: 6),
                      GestureDetector(
                        onTap: _addComment,
                        child: Container(width: 34, height: 34, decoration: const BoxDecoration(color: AppColors.gold, shape: BoxShape.circle), child: const Icon(Icons.send_rounded, color: AppColors.dark, size: 15)),
                      ),
                    ],
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }
}
