import 'dart:convert';
import '../services/l10n.dart';

/// Port of the website's autogenerated-post helpers (`components/Home/Post.tsx`):
/// which change rows are shown, how they are labelled and how values are masked.
class MetaRow {
  final String key;
  final String label;
  final String value;
  const MetaRow(this.key, this.label, this.value);
}

const _hiddenKeys = {
  'status', 'active', 'is_active', 'responsible_name', 'manager_name', 'postal_code', 'city_id',
  'country_code', 'phone_code', 'start_date', 'end_date', 'image', 'image_path', 'video',
  'video_path', 'file_name',
};

const _hiddenLabels = [
  'الحالة', 'اسم المسؤول', 'رمز المدينة', 'مفتاح الدولة', 'رمز الدولة', 'تاريخ البداية',
  'تاريخ النهاية', 'تاريخ البدء', 'تاريخ الانتهاء', 'ملف الصورة', 'ملف الفيديو', 'اسم الملف', 'اسم الفيديو',
];

bool _isEmpty(String? v) => v == null || v.isEmpty || v == '[]' || v == '—' || v == '-' || v == 'null';

String? _localeSuffix(String key) {
  for (final c in const ['ar', 'en', 'tr']) {
    if (key.endsWith('_$c')) return c;
  }
  return null;
}

String _cleanLabel(String s) => s
    .replaceAll(RegExp(r'\s*\([^)]*(?:عربي|إنجليزي|English|Arabic|Turkish|Türkçe)[^)]*\)', caseSensitive: false), '')
    .replaceAll('العنوان الكامل', 'العنوان')
    .trim();

String _rowLabel(Map<String, dynamic> row) {
  final labelAr = (row['label_ar'] as String?) ?? '';
  final sanitized = labelAr
      .replaceAll(RegExp(r'\s*\(عربي[ةه]?\)'), '')
      .replaceAll(RegExp(r'\s*\(إنجليزي[ةه]?\)'), '')
      .replaceAll('العنوان الكامل', 'العنوان');
  if (sanitized.isNotEmpty) {
    final key = 'post.metadata_fields.$sanitized';
    final translated = L10n.i.t(key, '');
    if (translated.isNotEmpty && translated != key) return translated;
  }
  final combined = '${row['label_ar'] ?? ''} ${row['label_en'] ?? ''} ${row['label_tr'] ?? ''}';
  if (RegExp(r'activity areas|مجالات النشاط|faaliyet alan', caseSensitive: false).hasMatch(combined)) {
    final s = L10n.i.t('post.metadata_fields.مجالات النشاط', '');
    if (s.isNotEmpty) return s;
  }
  final lang = L10n.i.lang;
  final pick = lang == 'ar'
      ? row['label_ar']
      : lang == 'tr'
          ? (row['label_tr'] ?? row['label_en'])
          : (row['label_en'] ?? row['label_tr']);
  return _cleanLabel('${pick ?? row['label_ar'] ?? row['label_en'] ?? ''}');
}

List<MetaRow> _fromChangeRows(dynamic rows) {
  if (rows is! List || rows.isEmpty) return [];
  final structural = <Map<String, dynamic>>[];
  for (final r in rows) {
    if (r is! Map) continue;
    final row = Map<String, dynamic>.from(r);
    final key = (row['key'] as String?) ?? '';
    final nv = row['new'] as String?;
    final value = _isEmpty(nv) ? ((row['old'] as String?) ?? '') : (nv ?? '');
    if (key.isEmpty || _hiddenKeys.contains(key)) continue;
    if (key.endsWith('_id') || key.endsWith('_at')) continue;
    final la = (row['label_ar'] as String?) ?? '';
    if (_hiddenLabels.any(la.contains)) continue;
    if (_isEmpty(value)) continue;
    row['_value'] = value;
    structural.add(row);
  }
  final present = <String>{for (final r in structural) if (_localeSuffix(r['key'] as String) != null) _localeSuffix(r['key'] as String)!};
  final lang = L10n.i.lang;
  final order = lang == 'ar' ? ['ar', 'en', 'tr'] : lang == 'tr' ? ['tr', 'en', 'ar'] : ['en', 'tr', 'ar'];
  final preferred = order.cast<String?>().firstWhere((c) => present.contains(c), orElse: () => null);
  return [
    for (final r in structural)
      if (_localeSuffix(r['key'] as String) == null || (preferred != null && _localeSuffix(r['key'] as String) == preferred))
        MetaRow(r['key'] as String, _rowLabel(r), r['_value'] as String),
  ];
}

/// Fallback: rows recovered from the plain text ("• label: before «x» → after «y»").
List<MetaRow> _fromContent(String? content) {
  if (content == null || content.isEmpty) return [];
  final lines = content.split(RegExp(r'\r?\n|(?=\s[-•]\s)')).map((l) => l.trim()).where((l) => l.isNotEmpty).toList();
  if (lines.length < 2) return [];
  final out = <MetaRow>[];
  for (final line in lines.skip(1)) {
    final bullet = line.replaceFirst(RegExp(r'^[•\-]\s*'), '');
    final m = RegExp(r'^(.+?):\s*').firstMatch(bullet);
    if (m == null) continue;
    final label = m.group(1)!.trim();
    final rest = bullet.substring(m.end).trim();
    final after = RegExp(r'(?:after|بعد)\s*[«"]([\s\S]*)[»"]\.?\s*$', caseSensitive: false).firstMatch(rest);
    final created = after == null ? RegExp(r'^[«"]([\s\S]*)[»"]\.?\s*$').firstMatch(rest) : null;
    var value = (after?.group(1) ?? created?.group(1) ?? '').trim();
    if (value.isEmpty) {
      value = rest.replaceFirst(RegExp(r'^(?:before|قبل)\s*[«"][\s\S]*?[»"]\s*(?:→|←)?\s*(?:after|بعد)?\s*', caseSensitive: false), '').trim();
    }
    value = value.replaceAll(RegExp(r'^[«"]|[»"]\.?\s*$'), '').trim();
    if (label.isEmpty || _isEmpty(value)) continue;
    final lower = label.toLowerCase();
    if (lower.endsWith(' id') || lower.contains('_id') || lower.contains('factory_step') || RegExp(r'_tr\b').hasMatch(lower)) continue;
    out.add(MetaRow('from_content', _cleanLabel(label), value));
  }
  return out;
}

List<MetaRow> visibleRows(Map<String, dynamic>? metadata, String content) {
  final fromMeta = _fromChangeRows(metadata?['change_rows']);
  return fromMeta.isNotEmpty ? fromMeta : _fromContent(content);
}

String contentLead(String content) {
  if (content.isEmpty) return '';
  final first = content.split(RegExp(r'\r?\n')).first.trim();
  final lead = first.split(RegExp(r'(?=\s[-•]\s)')).first;
  return lead.replaceFirst(RegExp(r':\s*saved fields:?\s*$', caseSensitive: false), '').trim();
}

String contentDetailBody(String content) {
  final lead = contentLead(content);
  if (lead.isEmpty) return content.trim();
  final idx = content.indexOf(lead);
  final rest = (idx >= 0 ? content.substring(idx + lead.length) : content).replaceFirst(RegExp(r'^[\s:\-–—]+'), '').trim();
  return rest == lead ? '' : rest;
}

String extractName(String header) {
  final m = RegExp(r'«([^»]+)»|\(([^)]+)\)|"([^"]+)"').firstMatch(header);
  final name = m == null ? '' : (m.group(1) ?? m.group(2) ?? m.group(3) ?? '');
  return cleanName(name);
}

String cleanName(String? name) {
  if (name == null) return '';
  return name.replaceAll(RegExp(r'\b(admin|ادمن|الأدمن|الادمن|إدارة|الادارة|الإدارة)\b', caseSensitive: false), '').replaceAll(RegExp(r'\s+'), ' ').trim();
}

/// "Section updated («name»)" title, translated with the site's `post.*` strings.
String activityHeader(String lead) {
  if (lead.isEmpty) return '';
  final name = extractName(lead);
  final l = lead.toLowerCase();
  String? key;
  if (l.contains('about section updated') || l.contains('تحديث النبذة')) {
    key = 'post.about_updated';
  } else if (l.contains('activity areas updated') || l.contains('تحديث مجالات')) {
    key = 'post.activities_updated';
  } else if (l.contains('created a new factory') || l.contains('إنشاء ملف')) {
    key = 'post.factory_created';
  } else if (l.contains('contact info updated') || l.contains('تحديث بيانات الاتصال')) {
    key = 'post.contact_updated';
  } else if (l.contains('branch updated')) {
    key = 'post.branch_updated';
  } else if (l.contains('added a new client')) {
    key = 'post.added_new_client';
  } else if (l.contains('added members to factory team') || l.contains('إضافة أعضاء إلى فريق المصنع') || l.contains('factory_team')) {
    key = 'post.added_new_team_member';
  } else if (l.contains('added a new banner') || l.contains('إضافة بانر جديد') || l.contains('banner')) {
    key = 'post.added_new_banner';
  } else if (l.contains('added a new image to the gallery') || l.contains('إضافة صورة للمعرض') || l.contains('factory_image') || l.contains('image_added')) {
    key = 'post.added_new_factory_image';
  } else if (l.contains('added a new video') || l.contains('إضافة فيديو') || l.contains('video_added') || l.contains('video')) {
    key = 'post.added_new_video';
  }
  if (key == null) return cleanName(lead);
  final label = L10n.i.t(key);
  return name.isEmpty ? label : '$label («$name»)';
}

bool isLtrValue(String value, String key, String label) {
  final k = key.toLowerCase();
  return value.contains('@') ||
      k.contains('email') || k.contains('phone') || k.contains('contact') || k.contains('mobile') || k.contains('url') || k.contains('link') ||
      label.contains('البريد') || label.contains('الهاتف') || label.contains('تواصل') || label.contains('رابط') ||
      RegExp(r'^\+?[0-9\s-]{8,}$').hasMatch(value);
}

/// Values shown in the green pill: arrays joined, e-mails and phones masked like the website.
List<String> formatValue(String value, String key, String label) {
  try {
    final parsed = jsonDecode(value);
    if (parsed is List) {
      final items = parsed.map((e) => '${e ?? ''}'.trim()).where((e) => e.isNotEmpty).toList();
      return items.isEmpty ? ['—'] : items;
    }
  } catch (_) {}
  final k = key.toLowerCase();
  if (value.contains('@') || k.contains('email') || label.contains('البريد')) {
    final parts = value.split('@');
    if (parts.length == 2) {
      final name = parts[0];
      return ['${name.length > 3 ? name.substring(0, 3) : name}***@${parts[1]}'];
    }
  }
  if (k.contains('phone') || k.contains('contact') || k.contains('mobile') || label.contains('الهاتف') || label.contains('تواصل') || RegExp(r'^\+?[0-9\s-]{8,}$').hasMatch(value)) {
    if (value.length > 7) return ['${value.substring(0, 4)} **** ${value.substring(value.length - 3)}'];
  }
  return [value];
}
